//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DareZameen_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaWisePrice
    {
        public int Id { get; set; }
        public Nullable<int> SpecialLocationId { get; set; }
        public Nullable<int> PropertyTypeId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<decimal> Size { get; set; }
        public Nullable<decimal> AveragePrice { get; set; }
        public Nullable<decimal> PlusMinus { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual SpecialLocation SpecialLocation { get; set; }
    }
}
