//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DareZameen_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedLocation
    {
        public int Id { get; set; }
        public int SpecialLocationId { get; set; }
        public int AgentId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual SpecialLocation SpecialLocation { get; set; }
    }
}
