//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DareZameen_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealStateDataEntities : DbContext
    {
        public RealStateDataEntities()
            : base("name=RealStateDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<AreaWisePrice> AreaWisePrice { get; set; }
        public virtual DbSet<AssignedLocation> AssignedLocation { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<InventoryUtlities> InventoryUtlities { get; set; }
        public virtual DbSet<PropertyType> PropertyType { get; set; }
        public virtual DbSet<Reference> Reference { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<SpecialLocation> SpecialLocation { get; set; }
        public virtual DbSet<Utilities> Utilities { get; set; }
    }
}
