//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DareZameen_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Room1 = new HashSet<Room>();
        }
    
        public int Id { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public Nullable<int> RoomType { get; set; }
        public Nullable<decimal> Size { get; set; }
        public Nullable<int> Windows { get; set; }
        public Nullable<bool> IsAttachedBath { get; set; }
        public Nullable<int> AttachedBathId { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Room1 { get; set; }
        public virtual Room Room2 { get; set; }
    }
}
